### ISSUE TITLE
question: operator= in getProp<>() in DEM example and tiny fix in normal force equation

### ISSUE THREAD

**Issue by ZhouleiJoeStone** [IBirdSoft/openfpm_pdata_2.0.0#2]
Hello, 
I have some question about the operator= in **getProp<>()**  .
In the DEM [example](https://github.com/IBirdSoft/openfpm_pdata_2.0.0/blob/master/example/Vector/8_DEM/main.cpp)

line 586-590 , the force and tau of  wall particle is set to be zero to make them keep static.

```
		    if (parts.getProp<tt>(p) == 1)
		    {
		    	parts.getProp<force>(p) = 0;
		    	parts.getProp<tau>(p) = 0;
		    }
```
# question :
 "0 is scalar, but force and tau is Point<3,double>". Does it use operator overloading in openfpm_pdata_2.0.0/openfpm_numerics/src/Operators/Vector/vector_dist_operators.hpp line 540-554 ?

```
	vector & operator=(double d)
	{
		auto it = v.getDomainIterator();

		while (it.isNext())
		{
			auto key = it.get();

			pos_or_propL<vector,prp>::value(v,key) = d;

			++it;
		}

		return v;
	}
```
# tiny fix:

in line 553 in DEM [example](https://github.com/IBirdSoft/openfpm_pdata_2.0.0/blob/master/example/Vector/8_DEM/main.cpp)

```

	double gamma_n = 3401;
	double gamma_t = 3401;
...

line 553:  Point<3,double> F_nij = sqrt(delta_ij/2/R) * (k_n*delta_ij*n_ij - gamma_t*m_eff*v_nij);
```
I think that the gamma_t in line 553 should  be gamma_n, although the gamma_n has the same value as gamma_t  in your exampe. It will be better to keep consistent with the equation in example webpage

$$
\vec{F}_{n_{ij}}=\sqrt{\frac{\delta_{ij}}{2R}}\,\,\left(k_n\delta_{ij}\vec{n}_{ij}-\gamma_n* m_{\text{eff}}\vec{v}_{n_{ij}}\right)
$$

**Comment by incardon** [comment]
> "0 is scalar, but force and tau is Point<3,double>". Does it use operator overloading in openfpm_pdata_2.0.0/openfpm_numerics/src/Operators/Vector/vector_dist_operators.hpp line 540-554 ?

Yes it use operator overload, but of Point<3,double>. So 
https://github.com/IBirdSoft/openfpm_data_2.0.0/blob/da7bebf0e5101b3e0e85e42695d755d843f7c418/src/Space/Shape/Point.hpp

line 574

> tiny fix:

Correct, thanks for reportinf

**Comment by incardon** [comment]
Now fixed
